#!/usr/bin/env python3
"""Build the embedded web UI bundle.

Reads webui/index.html, inlines referenced <link rel='stylesheet'> and
<script src='...'></script> assets, gzips the result, and emits a C header
at Pala_One_2_1/src/web/generated/webui.gz.h containing the bytes as a
PROGMEM array consumed by src/web/app.cpp.

Dual invocation:
  - PlatformIO pre-script (see platformio.ini): runs automatically on every
    `pio run`, so PIO builds always see a fresh header.
  - Standalone CLI: `python scripts/build_webui.py`. Arduino IDE users run
    this manually after editing the webui/ sources before flashing.

CI runs the script and then `git diff --exit-code` on the generated header
to catch stale commits. Drift cannot reach main.

Output is byte-stable: gzip mtime is pinned to 0 so identical inputs
produce identical headers (no spurious diffs from rebuilds).
"""
from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

# PlatformIO loads this file with `Import` injected into globals; standalone
# Python doesn't. The try/except is how we detect which context we're in
# without forcing PIO devs to invoke the script differently. PIO's SCons
# loader doesn't set __file__, so when in PIO we take the repo root from
# env["PROJECT_DIR"] instead (matching scripts/build_info.py).
try:
    Import("env")  # noqa: F821 — provided by PlatformIO at script-load time
    _IN_PIO = True
    REPO_ROOT = Path(env["PROJECT_DIR"]).resolve()  # noqa: F821
except NameError:
    _IN_PIO = False
    REPO_ROOT = Path(__file__).resolve().parents[1]

WEBUI_DIR = REPO_ROOT / "webui"
SRC_HTML  = WEBUI_DIR / "index.html"
OUT_H     = REPO_ROOT / "Pala_One_2_1" / "src" / "web" / "generated" / "webui.gz.h"

# Matches <link rel='stylesheet' href='X'> with single or double quotes,
# self-closing or not. Trailing attributes after href would defeat this —
# keep our HTML simple enough that the regex suffices.
_CSS_LINK_RE = re.compile(
    r"""<link\s+rel=['"]stylesheet['"]\s+href=['"]([^'"]+)['"]\s*/?>""",
    re.IGNORECASE,
)
# Matches <script src='X'></script>. Inline <script> bodies pass through
# untouched.
_JS_SRC_RE = re.compile(
    r"""<script\s+src=['"]([^'"]+)['"]\s*></script>""",
    re.IGNORECASE,
)


def _inline_assets(html: str) -> str:
    """Replace external <link>/<script src> with their inline equivalents."""
    def inline_css(m: re.Match) -> str:
        css_path = WEBUI_DIR / m.group(1)
        if not css_path.is_file():
            sys.exit(f"build_webui.py: referenced stylesheet missing: {css_path}")
        body = css_path.read_text(encoding="utf-8")
        return f"<style>{body}</style>"

    def inline_js(m: re.Match) -> str:
        js_path = WEBUI_DIR / m.group(1)
        if not js_path.is_file():
            sys.exit(f"build_webui.py: referenced script missing: {js_path}")
        body = js_path.read_text(encoding="utf-8")
        # Defensive: a literal `</script>` inside the body would break the
        # surrounding tag. Split it across two strings the parser can't see
        # as a single close tag. (Comments are the realistic offender.)
        body = body.replace("</script>", "<\\/script>")
        return f"<script>{body}</script>"

    html = _CSS_LINK_RE.sub(inline_css, html)
    html = _JS_SRC_RE.sub(inline_js, html)
    return html


def _emit_c_header(data: bytes, src_size: int) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/build_webui.py — do not edit by hand.",
        "// Regenerate with `python scripts/build_webui.py` (Arduino IDE) or",
        "// any `pio run` (PlatformIO, via the pre-script).",
        f"// source: webui/index.html ({src_size} bytes -> {len(data)} bytes gzipped)",
        "#ifndef PALA_WEB_GENERATED_WEBUI_GZ_H",
        "#define PALA_WEB_GENERATED_WEBUI_GZ_H",
        "",
        "#include <Arduino.h>",
        "",
        "static const uint8_t kWebUiGz[] PROGMEM = {",
    ]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"  {chunk},")
    lines += [
        "};",
        f"static const size_t kWebUiGzLen = {len(data)};",
        "",
        "#endif  // PALA_WEB_GENERATED_WEBUI_GZ_H",
        "",  # trailing newline
    ]
    return "\n".join(lines)


def build() -> bool:
    """Regenerate the header. Returns True if the on-disk file changed."""
    if not SRC_HTML.is_file():
        sys.exit(f"build_webui.py: source missing: {SRC_HTML}")
    raw = SRC_HTML.read_text(encoding="utf-8")
    bundled = _inline_assets(raw)
    bundled_bytes = bundled.encode("utf-8")
    # mtime=0 keeps output byte-stable across rebuilds so the CI diff-check
    # only flips when source actually changed. We also pin the OS byte
    # (header byte 9) to 0xff "unknown" because Python's gzip module writes
    # it based on the host platform (0x00 on Windows, 0x03 on Unix, etc.)
    # — without this, the same source produces different bytes on CI vs a
    # dev machine and the freshness check randomly fails.
    gz = gzip.compress(bundled_bytes, compresslevel=9, mtime=0)
    gz = bytearray(gz)
    gz[9] = 0xff
    gz = bytes(gz)
    header = _emit_c_header(gz, len(bundled_bytes))
    existing = OUT_H.read_text(encoding="utf-8") if OUT_H.exists() else None
    if existing == header:
        return False
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(header, encoding="utf-8")
    return True


def _run() -> None:
    changed = build()
    state = "updated" if changed else "unchanged"
    print(f"build_webui.py: webui.gz.h {state}")


if _IN_PIO:
    _run()
elif __name__ == "__main__":
    _run()
